name: 'Deploy B4App'
description: 'Deploy to B4App'
author: "Murilo Henrique"
branding:
  icon: 'upload-cloud'  
  color: 'green'
inputs:
  project:  # id of input
    description: 'project name of b4app deploy'
    required: true
  accountKey:
    description: 'AccountKey of B4App account'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.project }}
    - ${{ inputs.accountKey }}